[build]
  command = "node -r dotenv/config ./scripts/build.js && npm run build"
  publish = ".next"
  edge_functions = "netlify/edge-functions"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  AWS_REGION = "ap-south-1"
  S3_BUCKET_NAME = "neverwrite-assets"
